config/routes.rb
Rails.application.routes.draw do
  get 'service_reviews/create'
  get "book_room", to: "services#book_room"
  get "pay", to: "services#pay"

  root "home#index"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers:{omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users, only: %i(index show destroy) do
    resources :schedules, only: %i(index create destroy) do
      resources :schedule_items, only: %i(index destroy edit create)
    end
  end
  get "/search", to: "home#search"
  get "services", to: "services#index"
  get "services/:id/confirm" , to: "services#confirm", :as => :service_confirm
  get "services/categories/:category_id", to: "services#index", :as => :service_categories
  get "services/:id" , to: "services#show", :as => :service_details
  resources :service_reviews, only: %i(create destroy)

  get "service_bookings/payment" , to: "service_bookings#payment", :as => :service_payment
  resources :service_bookings
  get "services_in_place/:place_id", to: "services#services_in_place", :as => :services_in_place

end

app/models/service.rb
class Service < ApplicationRecord
  resourcify
  belongs_to :provider
  belongs_to :category
  belongs_to :place
  has_many :service_images, dependent: :destroy
  has_many :service_reviews
  scope :get_services, ->(place_id,start_time, end_time){where("place_id = ?", place_id).where("start_time = ?", start_time.to_datetime).where("end_time = ?", end_time.to_datetime)}
  scope :get_by_category, ->(id){where("category_id = ?", id)}
  scope :get_services_in_place, ->(id){where("place_id = ?", id)}
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :load_services_by_category, only: %i(index)

  def index
    @categories = Category.all
  end

  def show
    @service = Service.find_by id: params[:id]
    @service_reviews = @service.service_reviews.order('created_at DESC').page(params[:page]).per(Settings.page.num_of_reviews)
    redirect_to root_url if @service.nil?
  end

  def book_room
    render "book_room"
  end

  def confirm
    @service = Service.find_by id: params[:id]
  end

  def services_in_place
      @services = Service.get_services_in_place(params[:place_id]).page(params[:page]).order('price DESC').per(Settings.page.num_of_services)
  end

  private
  def load_services_by_category
    if params[:category_id]
      @services = Service.get_by_category(params[:category_id]).page(params[:page]).order('price DESC').per(Settings.page.num_of_services)
    else
      @services = Service.all.page(params[:page]).order('price DESC').per(Settings.page.num_of_services)
    end
  end
end

app/views/services/_detail.html.erb
<div class="hotellist-item hotel-detail">
    <div class="hotel-head">
        <div class="row hotel-name">
            <div class="col-xs-12 col-sm-9">
                <h3>
                    <a href="#">
                        <%= service.name %>
                    </a>
                </h3>

            </div>
        </div>
        <!-- .hotel-name -->
        <div class="hotel-slider">
            <div class="row gallery-photos clearfix">
                <div class="col-xs-12 col-sm-8 hotel-slider">
                    <div class="row">
                        <div class="col-sm-12" id="carousel-hotel-box">
                            <div class="carousel slide" id="hotelCarousel">
                                <!-- Carousel items -->
                                <div class="carousel-inner">
                                    <% @service.service_images.each_with_index do |img, i| %>
                                        <div class="item <%= (i == 0)? 'active': '' %>" data-slide-number="<%= i %>">
                                          <%= image_tag(img.link, class: "resize-slide", alt: "Service") %>
                                        </div>
                                    <% end %>
                                </div>
                                <!-- Carousel nav -->
                                <a class="left carousel-control" href="#hotelCarousel" role="button" data-slide="prev">
                                    <span class="fa fa-angle-left"></span>
                                </a>
                                <a class="right carousel-control" href="#hotelCarousel" role="button" data-slide="next">
                                    <span class="fa fa-angle-right"></span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="hotel-slider-thumbs" class="col-xs-12 col-sm-4">
                    <ul class="col-xs-12 no-padding hide-bullets">
                         <% @service.service_images.each_with_index do |img, i| %>
                            <li class="col-sm-3 <%= (i == 0)? 'active': '' %>" data-item-number="<%= i %>">
                              <%=link_to image_tag(img.link,class: "resize-slide-item", alt: "Service"), "#", class: "thumbnail", id: "carousel-hotel-#{i}"  %>
                            </li>
                        <% end %>
                    </ul>
                    <div class="col-xs-12 no-padding hotellist-price">

                        <h5 class="text-left text-blue"><strong>Start time:</strong>
                            <% if service.start_time %>
                                <%= service.start_time.strftime("%B %d, %Y") %>
                            <% end %>
                        </h5>
                        <h5 class="text-left text-blue"><strong>End time:</strong>
                            <% if service.end_time %>
                                <%= service.end_time.strftime("%B %d, %Y") %>
                            <% end %>
                        </h5>
                        <h2 class="text-left text-blue price-ht">USD <span class="text-yellow"><%= service.price %></span></h2>

                    </div>
                    <div class="col-xs-12 no-padding hotel-slide-pay">
                        <p class="text-blue"><%= t "cards_accepted" %></p>
                        <ul class="list-inline">
                            <li><%= link_to image_tag("pay1.png", class: "img-responsive"), "#" %></li>
                            <li><%= link_to image_tag("pay2.png", class: "img-responsive"), "#" %></li>
                            <li><%= link_to image_tag("pay3.png", class: "img-responsive"), "#" %></li>
                            <li><%= link_to image_tag("pay4.png", class: "img-responsive"), "#" %></li>
                        </ul>
                    </div>
                    <div>
                    <% if user_signed_in? %>
                        <%= render "service_bookings/booking_form" %>
                    <% end %>
                    </div>

                </div>
            </div>
        </div>
        <!-- .hotel-slider -->
    </div>
    <!-- .hotel-head -->
</div>

app/views/services/_filter_hotel.html.erb
<div class="col-xs-12 col-sm-3 page-left filter-left-mb__overlay">
    <div class="filter-head__overlay">
        <h3><%= t "Filter" %></h3>
        <span class="fa fa-close filter-head-close__overlay"></span>
    </div>
    <div class="filter-left">
        <% @categories.each do |category| %>
            <filter class="box box-filter-budget">
                <div class="filter-title">
                    <%= link_to category.name, service_categories_path(category.id) %>
                </div>
            </filter>
        <% end %>
    </div>
    <!-- .Filter left -->
</div>

app/views/services/book_room.html.erb
  <div id="booking" class="section">
    <div class="section-center">
      <div class="container">
        <div class="row">
          <div class="booking-form">
            <div class="form-header">
              <h1>Make your reservation</h1>
            </div>
            <form action="pay">
              <div class="form-group">
                <input class="form-control" type="text" placeholder="Country, ZIP, city...">
                <span class="form-label">Destination</span>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <input class="form-control" type="date" required>
                    <span class="form-label">Check In</span>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <input class="form-control" type="date" required>
                    <span class="form-label">Check out</span>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-4">
                  <div class="form-group">
                    <select class="form-control" required>
                      <option value="" selected hidden>no of rooms</option>
                      <option>1</option>
                      <option>2</option>
                      <option>3</option>
                    </select>
                    <span class="select-arrow"></span>
                    <span class="form-label">Rooms</span>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <select class="form-control" required>
                      <option value="" selected hidden>no of adults</option>
                      <option>1</option>
                      <option>2</option>
                      <option>3</option>
                    </select>
                    <span class="select-arrow"></span>
                    <span class="form-label">Adults</span>
                  </div>
                </div>
                <div class="col-md-4">
                  <div class="form-group">
                    <select class="form-control" required>
                      <option value="" selected hidden>no of children</option>
                      <option>0</option>
                      <option>1</option>
                      <option>2</option>
                    </select>
                    <span class="select-arrow"></span>
                    <span class="form-label">Children</span>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <input class="form-control" type="email" placeholder="Enter your Email">
                    <span class="form-label">Email</span>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <input class="form-control" type="tel" placeholder="Enter you Phone">
                    <span class="form-label">Phone</span>
                  </div>
                </div>
              </div>
              <div class="form-btn">
                <button class="btn btn-yellow btn-select-room">Book Now</button>
              </div>
            </form>
            <br>
          </div>
        </div>
      </div>
    </div>
  </div>

  <script src="js/jquery.min.js"></script>
  <script>
    $('.form-control').each(function () {
      floatedLabel($(this));
    });

    $('.form-control').on('input', function () {
      floatedLabel($(this));
    });

    function floatedLabel(input) {
      var $field = input.closest('.form-group');
      if (input.val()) {
        $field.addClass('input-not-empty');
      } else {
        $field.removeClass('input-not-empty');
      }
    }
  </script>

app/views/services/confirm.html.erb
<% provide(:title,"Rooms")%>
<body style="background: #eef3f7">
  <div class="row">
   <div class="md-stepper-horizontal orange">
      <div class="md-step ok">
        <div class="md-step-circle"><span>1</span></div>
        <div class="md-step-title">User information</div>
        <div class="md-step-bar-left"></div>
        <div class="md-step-bar-right"></div>
      </div>
      <div class="md-step ok">
        <div class="md-step-circle"><span>2</span></div>
        <div class="md-step-title">Payment details</div>
        <div class="md-step-bar-left"></div>
        <div class="md-step-bar-right"></div>
      </div>
      <div class="md-step active">
        <div class="md-step-circle"><span>3</span></div>
        <div class="md-step-title">Service Booked confirm</div>
        <div class="md-step-bar-left"></div>
        <div class="md-step-bar-right"></div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row" >
        <div class="col-md-12">
            <div class=" review_listing">
                <h3 class = "success-text"><i class="fas fa-check-circle"></i> Service booked successful</h3>
                <hr>
                <div class="well confident-message m-t-1 m-b-0">
                    <ul class="list-default m-b-0" data-bind="foreach: messageItemList()">
                        <li data-bind="html: $data.text, css: $data.className" class="chosen-to-pay-by">You booked this service<%= @service.name %> at <%= Time.now %></li>
                    <!--    <li data-bind="html: $data.text, css: $data.className" class="note-that-choosing-to-pay-by"></li>-->
                    </ul>
                </div>
                <hr>
                 <%= link_to "Homepage", root_path, {class: "btn btn-primary btn-sm"} %>
            </div>
        </div>
    </div>
  </div>
</body>

app/views/services/index.html.erb
<% provide(:title,"Rooms")%>
<%= render "layouts/search_form" %>
<div class="full-row page-content">
  <div class="container no-padding">
    <%= render "filter_hotel", locals: { categories: @categories } %>
    <div class="col-xs-12 col-sm-9 page-right">
      <div class="filter-result">
        
      <div class="container packages_home">

        
        <% @services.each do |service| %>
          <div class="col-xs-6 col-sm-6 col-md-4 package_item" style="height: 200px; width:300px">
            <div class="package_item_content">
                <%= link_to image_tag(service.service_images.first.link,  class: "img-responsive", style: "height: 150px; width:250px"), service_details_path(service.id) %>
                <div class="thumb_content fullwidth" style="height: 50px; width:250px">
                    <div class="thumb_title">
                        <div class="tour_country">
                          <%= service.place.name %>
                        </div>
                    </div>
                    
                </div>
            </div>
          </div>
        <% end %>
        </div>
        <%= paginate @services, theme: 'twitter-bootstrap-3' %>
        
      </div>
    </div>
  </div>
</div>

app/views/services/pay.html.erb
    <div class="container-fluid">

        <div class="creditCardForm">
            <div class="heading">
                <h1>Confirm Purchase</h1>
            </div>
            <div class="col-xs-5">
                <form action="/">
                    <div class="form-group owner">
                        <label for="owner">Owner</label>
                        <input type="text" class="form-control" id="owner">
                    </div>
                    <div class="form-group CVV">
                        <label for="cvv">CVV</label>
                        <input type="text" class="form-control" id="cvv">
                    </div>
                    <div class="form-group" id="card-number-field">
                        <label for="cardNumber">Card Number</label>
                        <input type="text" class="form-control" id="cardNumber">
                    </div>
                    <div class="form-group" id="expiration-date">
                        <label>Expiration Date</label>
                        <select>
                            <option value="01">January</option>
                            <option value="02">February </option>
                            <option value="03">March</option>
                            <option value="04">April</option>
                            <option value="05">May</option>
                            <option value="06">June</option>
                            <option value="07">July</option>
                            <option value="08">August</option>
                            <option value="09">September</option>
                            <option value="10">October</option>
                            <option value="11">November</option>
                            <option value="12">December</option>
                        </select>
                        <select>
                            <option value="16"> 2016</option>
                            <option value="17"> 2017</option>
                            <option value="18"> 2018</option>
                            <option value="19"> 2019</option>
                            <option value="20"> 2020</option>
                            <option value="21"> 2021</option>
                        </select>
                    </div>
                    <div class="col-xs-12 no-padding hotel-slide-pay">
                        <p class="text-blue"><%= t "cards_accepted" %></p>
                        <ul class="list-inline">
                            <li><%= link_to image_tag("pay1.png", class: "img-responsive"), "#" %></li>
                            <li><%= link_to image_tag("pay2.png", class: "img-responsive"), "#" %></li>
                            <li><%= link_to image_tag("pay3.png", class: "img-responsive"), "#" %></li>
                            <li><%= link_to image_tag("pay4.png", class: "img-responsive"), "#" %></li>
                        </ul>
                    </div>
                    <div class="form-group" id="pay-now">
                        <button type="submit" class="btn btn-yellow btn-select-room" id="confirm-purchase" onclick="myFunction()">Thanh toán</button>
                    </div>
                </form>
            </div>
        </div>
        <script>
            function myFunction() {
              alert("cảm ơn bạn đã sử dụng dịch vụ của chúng tôi!");
            }
        </script>
        <p class="examples-note">Here are some dummy credit card numbers and CVV codes so you can test out the form:</p>

        <div class="examples">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Type</th>
                            <th>Card Number</th>
                            <th>Security Code</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Visa</td>
                            <td>4716108999716531</td>
                            <td>257</td>
                        </tr>
                        <tr>
                            <td>Master Card</td>
                            <td>5281037048916168</td>
                            <td>043</td>
                        </tr>
                        <tr>
                            <td>American Express</td>
                            <td>342498818630298</td>
                            <td>3156</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

app/views/services/services_in_place.html.erb
<% provide(:title,"Rooms")%>
<%= render "layouts/search_form" %>
<div class="full-row page-content">
  <div class="container no-padding">

    <div class="col-xs-12 col-sm-9 page-right">
        
      <div class="container packages_home">

        <% @services.each do |service| %>
          <div class="col-xs-6 col-sm-6 col-md-4 package_item">
            <div class="package_item_content">
                <%= link_to image_tag(service.service_images.first.link,  class: "img-responsive custom-size-image"), service_details_path(service.id) %>
                <div class="thumb_content fullwidth">
                    <div class="thumb_title">
                        <div class="tour_country">
                          <%= service.place.name %>
                        </div>
                    </div>
                    
                </div>
            </div>
          </div>
        <% end %>
        </div>
    </div>
  </div>
  <center><%= paginate @services, theme: 'twitter-bootstrap-3' %></center>
</div>

app/views/services/show.html.erb
<% provide(:title,"Rooms")%>
<%= render "layouts/search_form" %>
<div class="full-row page-content">
  <div class="container no-padding">
    <div class="col-xs-12 col-sm-12 page-right">
      <div class="filter-result">
        <%= render :partial => "detail", :locals => {:service => @service} %>
        <div class="hotellist-item hotel-detail">
            <strong><h2><%= t "DESCRIPTION" %></h2></strong>
            <%= @service.description %>
        </div>
        <div class="hotellist-item hotel-detail">
          <strong><h2><%= t "reviews" %></h2></strong>
          <div class = "container">
            <% if user_signed_in? %>
               <%= render :partial => "service_reviews/create" %>
            <% end %>
            <%= render :partial => "service_reviews/show", :locals => {:service_reviews => @service_reviews, :service => @service} %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>