config/routes.rb
Rails.application.routes.draw do
  get 'service_reviews/create'
  get "book_room", to: "services#book_room"
  get "pay", to: "services#pay"

  root "home#index"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers:{omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users, only: %i(index show destroy) do
    resources :schedules, only: %i(index create destroy) do
      resources :schedule_items, only: %i(index destroy edit create)
    end
  end
  get "/search", to: "home#search"
  get "services", to: "services#index"
  get "services/:id/confirm" , to: "services#confirm", :as => :service_confirm
  get "services/categories/:category_id", to: "services#index", :as => :service_categories
  get "services/:id" , to: "services#show", :as => :service_details
  resources :service_reviews, only: %i(create destroy)

  get "service_bookings/payment" , to: "service_bookings#payment", :as => :service_payment
  resources :service_bookings
  get "services_in_place/:place_id", to: "services#services_in_place", :as => :services_in_place

end

app/models/service_booking.rb
class ServiceBooking < ApplicationRecord
  belongs_to :user
  belongs_to :service
  belongs_to :payment_method
  belongs_to :booking_status

  before_create :set_booking_status

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :user_id, presence: true
  validates :service_id, presence: true
  validates :booking_address, presence: true
  validates :payment_method_id, presence: true
  validates :booking_user, presence: true
  validates :booking_status, presence: true

  def subtotal

  end

  def user_name
    self.user.name
  end

  def generate_qr text
    chart = GoogleQR.new(:data => "#{text}", :size => "250x250", :margin => 4, :error_correction => "L")
    return chart.to_s
  end

  private
  def set_booking_status
    self.booking_status_id = 1
  end

end

app/controllers/service_bookings_controller.rb
class ServiceBookingsController < ApplicationController
    before_action :authenticate_user!

    def index
    end

    def new
        @payment_methods = PaymentMethod.all
        @service = Service.find_by(id:params[:service_id])
        total_price = (@service.price.to_f * params[:quantity].to_f).round(2)
        @jcart = {'quantity' => params[:quantity],
                  'service' => @service.attributes,
                    'unit_price'=> @service.price,
                    'total_price'=> total_price }
        render "book"
    end

    def create
        @booking = current_user.service_bookings.build booking_params
        @booking.save!
        @confirm_secret_key = "booking_id:" + @booking.id.to_s + "_" +
                      + "user_id:" + @booking.user_id.to_s + "_" +
                      + "service_id:" + @booking.service_id.to_s + "_" +
                      + "book at:" + @booking.created_at.to_s
        @booking.update_attributes confirm_secret_key: @confirm_secret_key
        # ConfirmBookingMailer.confirm_booking_mail(current_user,@booking).deliver
        render "confirm"
    end

    def payment
        @jcart = params[:jcart]
        service_id = @jcart['service']['id']
        @service = Service.find_by(id: service_id)
        render "payment"
    end

    def booking_params
        params.require(:service_booking).permit :user_id,
                                                :service_id,
                                                :booking_user,
                                                :booking_address,
                                                :quantity,
                                                :unit_price,
                                                :total_price,
                                                :payment_method_id,
                                                :booking_status_id
    end
end

app/helpers/service_bookings_helper.rb
module ServiceBookingsHelper
end

app/views/service_bookings/_booking_form.html.erb
<%= form_tag new_service_booking_path,method: :get do |f|%>
<%= hidden_field_tag :service_id, @service.id %>
<h3 class="text-yellow"><b><%=number_to_currency @service.price %></b></h3>
<%= select_tag :quantity, options_for_select(1..15),:id => "quantity_selection" %>
<h3 class="text-yellow"><b>$<span id ="total_price"><%= @service.price %></span></b></h3>
<%=submit_tag "book",{ class: "btn btn-blue btn-reserve", style: "float:right;"} %>    
<% end %>
<script>
$("#quantity_selection").on("change", function() {
  var service_price = <%= @service.price %>
  total_price = this.value * service_price
  total_price = total_price.toFixed(2)
  $("#total_price").html(total_price);
});
</script>

app/views/service_bookings/book.html.erb
<% provide(:title,"Rooms")%>
<body style="background: #eef3f7">
  <div class="row">
    <div class="md-stepper-horizontal orange">
      <div class="md-step active">
        <div class="md-step-circle"><span>1</span></div>
        <div class="md-step-title">User information</div>
        <div class="md-step-bar-left"></div>
        <div class="md-step-bar-right"></div>
      </div>
      <div class="md-step">
        <div class="md-step-circle"><span>2</span></div>
        <div class="md-step-title">Payment details</div>
        <div class="md-step-bar-left"></div>
        <div class="md-step-bar-right"></div>
      </div>
      <div class="md-step">
        <div class="md-step-circle"><span>3</span></div>
        <div class="md-step-title">Service Booked confirm</div>
        <div class="md-step-bar-left"></div>
        <div class="md-step-bar-right"></div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row" >
      <div class="col-md-8">
        <%= form_for(current_user.service_bookings.build ) do |f| %>
          <div class="review_listing">
            <h3>1. Billing Address</h3>
            <hr>
            <%= f.label :booking_user, class: "col-form-label" do%>
            <i class="fa fa-address-card-o"></i> Booking user name(*)
            <% end %>
            <%= f.text_field :booking_user, required: true, placeholder: "Full name" %>
            
            <%= f.label :booking_user, class: "col-form-label" do %>
             <i class="fa fa-address-card-o"></i> Address
            <% end %>
            <%= f.text_field :booking_address, required: true, placeholder: "House number, Street, City,..." %>
            
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.hidden_field :booking_status_id, value: 1 %>
            <%= f.hidden_field :quantity, value: @jcart['quantity'] %>
            <%= f.hidden_field :service_id, value: @jcart['service']['id'] %>
            <%= f.hidden_field :unit_price, value: @jcart['unit_price'] %>
            <%= f.hidden_field :total_price, value: @jcart['total_price'] %>
    		  </div>     
          <div class=" review_listing">
          <h3>2. Payment</h3>
          <hr>
             <div class="radio-selections">
           
            
           <% @payment_methods.each do |option| %>
              <%= f.radio_button :payment_method_id, "#{option.id}" %><%= f.label :payment_method_id, value: "#{option.name}" %>
            <% end %>
          </div>
          <p>You can use Paypal to pay</p>
          <%= link_to image_tag("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6BxA5RfMz5ZnCLJw_1S7-iWYNlt6aJfYolVCR-sVOAEtxg_1ayg&s",width: "100px", height: "50px"), service_payment_path(:jcart => @jcart) %></a>
        </div>
        <%= f.submit "Checkout",{class: "btn btn-success"} %>
        <% end %>
  		</div>
  		<div class="col-md-4  cart-items">
        <div class=" review_listing" style="display: flex">
          <a href="">
            <% @service.service_images.each_with_index do |img, i| %>
            <% if(i == 0) %>
              <%=link_to image_tag(img.link, width: "100", height: "130"), "#", width: "100px"  %>
            <% end %>
            <% end %>
            </a>
          <div style="margin-left: 10px">
            <h4><b><%= @service.name %></b></h4>
            <p>Provider: <%= @service.provider.name %></p>
            <p>Start time: <% if @service.start_time %>
                                <%= @service.start_time.strftime("%B %d, %Y") %>
                            <% end %></p>
            <p>End time: <% if @service.end_time %>
                            <%= @service.end_time.strftime("%B %d, %Y") %>
                        <% end %></p>
          </div>
        </div>  
        
        <div class=" review_listing">
          <div class="row">
            <div class="col-md-6">
              <h4>Unit Price</h4>
            </div>
            <div class="col-md-6">
              <h4><b><%=number_to_currency @jcart['unit_price'] %></b></h4>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <h4>Quantity</h4>
            </div>
            <div class="col-md-6">
              <h4><b><%=@jcart['quantity']%></b></h4>
            </div>
          </div>
          
          <div class="row">
            <div class="col-md-6">
              <h4>Discount</h4>
            </div>
            <div class="col-md-6">
              <h4><b>$0</b></h4>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-md-6">
              <h4>Total price</h4>
            </div>
            <div class="col-md-6">
              <h4 style="color: #00becc"><b><%= number_to_currency @jcart['total_price'] %></b></h4>
            </div>
          </div>   
          <div class="row">
            <div class="col-md-12">
              <p style="opacity: 0.5"><b>Included:</b> service 10%, tax 10%</p>
            </div>
          </div>
        </div>          
  		</div>
    </div>
  </div>
</body>

app/views/service_bookings/confirm.html.erb
<% provide(:title,"Rooms")%>
<body style="background: #eef3f7">
  <div class="row">
    <div class="md-stepper-horizontal orange">
      <div class="md-step ok">
        <div class="md-step-circle"><span>1</span></div>
        <div class="md-step-title">User information</div>
        <div class="md-step-bar-left"></div>
        <div class="md-step-bar-right"></div>
      </div>
      <div class="md-step ok">
        <div class="md-step-circle"><span>2</span></div>
        <div class="md-step-title">Payment details</div>
        <div class="md-step-bar-left"></div>
        <div class="md-step-bar-right"></div>
      </div>
      <div class="md-step active">
        <div class="md-step-circle"><span>3</span></div>
        <div class="md-step-title">Service Booked confirm</div>
        <div class="md-step-bar-left"></div>
        <div class="md-step-bar-right"></div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row" >
        <div class="col-md-12">
            <div class=" review_listing">
                <h3 class = "success-text"><i class="fas fa-check-circle"></i> Service booked successful</h3>
                <hr>
                <div class="well confident-message m-t-1 m-b-0">
                    <ul class="list-default m-b-0" data-bind="foreach: messageItemList()">
                         <li data-bind="html: $data.text, css: $data.className" class="chosen-to-pay-by">You booked this service<%= @booking.service.name %> at <%= Time.now %></li>
                       <!-- <li data-bind="html: $data.text, css: $data.className" class="note-that-choosing-to-pay-by"></li>-->
                    </ul>
                    <ul><a href="https://mail.google.com/" target="_blank">Click here to check in your mail</ul>
                </div>
                <hr>
                 <%= link_to "Homepage", root_path, {class: "btn btn-primary btn-sm"} %>
            </div>
        </div>
    </div>
  </div>
</body>

app/views/service_bookings/payment.html.erb
<% provide(:title,"Rooms")%>
<body style="background: #eef3f7">
  <div class="row">
    <div class="md-stepper-horizontal orange">
      <div class="md-step ok">
        <div class="md-step-circle"><span>1</span></div>
        <div class="md-step-title">User information</div>
        <div class="md-step-bar-left"></div>
        <div class="md-step-bar-right"></div>
      </div>
      <div class="md-step active">
        <div class="md-step-circle"><span>2</span></div>
        <div class="md-step-title">Payment details</div>
        <div class="md-step-bar-left"></div>
        <div class="md-step-bar-right"></div>
      </div>
      <div class="md-step">
        <div class="md-step-circle"><span>3</span></div>
        <div class="md-step-title">Service Booked confirm</div>
        <div class="md-step-bar-left"></div>
        <div class="md-step-bar-right"></div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row" >
        <div class="col-md-8">
            <div class=" review_listing">
                <h3>Pay by Paypal</h3>
                <hr>
                <div class="well confident-message m-t-1 m-b-0">
                    <ul class="list-default m-b-0" data-bind="foreach: messageItemList()">
                        <li data-bind="html: $data.text, css: $data.className" class="chosen-to-pay-by">You have choosed <strong>PayPal</strong> and need to leave website TripBricks then access <strong>PayPal</strong> to finish this transaction.&nbsp;</li>
                        <li data-bind="html: $data.text, css: $data.className" class="note-that-choosing-to-pay-by">Total price you need to pay: <strong><%= number_to_currency(@jcart['total_price']) %></strong></li>
                    </ul>
                </div>
                <p class="agoda-terms-and-conditions">To continue, i agreed with terms of use <a data-element-name="general-term-on-step2-link" href="//www.agoda.com/vi-vn/info/agoda-termsofuse.html" target="_blank"> of TripBricks</a> and agreed with their<a data-element-name="privacy-policy-on-step2-link" href="//www.agoda.com/vi-vn/info/agoda-privacy.html" target="_blank">Privacy Policy</a>.</p>
                <hr>
                <div id="paypal-button"></div>
                  <%= form_for(current_user.service_bookings.build,:html => {:id => "form"} ) do |f| %>
                    <%= f.hidden_field :booking_user, value: "vu huy khoi" %>
                    <%= f.hidden_field :booking_address, value: "hanoi, vietnam" %>
                    <%= f.hidden_field :user_id , value: current_user.id %>
                    <%= f.hidden_field :booking_status_id, value: 1 %>
                    <%= f.hidden_field :quantity, value: @jcart['quantity'] %>
                    <%= f.hidden_field :service_id, value: @jcart['service']['id'] %>
                    <%= f.hidden_field :unit_price, value: @jcart['unit_price'] %>
                    <%= f.hidden_field :total_price, value: @jcart['total_price'] %>
                    <%= f.hidden_field :payment_method_id, value: 2 %>
                    <%= f.submit "", :id => 'Submit', :style => "display: none;" %>
                  <% end %>
                <script src="https://www.paypalobjects.com/api/checkout.js"></script>
                <script>
                  paypal.Button.render({
                    // Configure environment
                    env: 'sandbox',
                    client: {
                      sandbox: 'demo_sandbox_client_id',
                      production: 'demo_production_client_id'
                    },
                    // Customize button (optional)
                    locale: 'en_US',
                    style: {
                      size: 'small',
                      color: 'gold',
                      shape: 'pill',
                    },
                
                    // Enable Pay Now checkout flow (optional)
                    commit: true,
                
                    // Set up a payment
                    payment: function(data, actions) {
                      return actions.payment.create({
                        transactions: [{
                          amount: {
                            total: '<%= @jcart['total_price'] %>',
                            currency: 'USD'
                          }
                        }]
                      });
                    },
                    // Execute the payment
                    onAuthorize: function(data, actions) {
                      return actions.payment.execute().then(function() {
                        // Show a confirmation message to the buyer
                        toastr.success('Thank you for your purchase!');
                        //window.location.href = "/services/<%= @service.id %>/confirm"
                        $("#form").submit();
                      });
                    }
                  }, '#paypal-button');
                
                </script>

            </div>
            <a href="/services/<%= @service.id %>/book" type="button" class="btn btn-default active">Turn back to payment details</a>
        </div>
  		<div class="col-md-4">
        <div class=" review_listing" style="display: flex">
          <a href="">
            <% @service.service_images.each_with_index do |img, i| %>
            <% if(i == 0) %>
              <%=link_to image_tag(img.link, width: "100", height: "130"), "#", width: "100px"  %>
            <% end %>
            <% end %></a>
          <div style="margin-left: 10px">
            <h4><b><%= @service.name %></b></h4>
            <p>Provider: <%= @service.provider.name %></p>
            <p>Start time: <% if @service.start_time %>
                                <%= @service.start_time.strftime("%B %d, %Y") %>
                            <% end %></p>
            <p>End time: <% if @service.end_time %>
                            <%= @service.end_time.strftime("%B %d, %Y") %>
                        <% end %></p>
          </div>
        </div>  
        <div class=" review_listing">
          <div class="row">
            <div class="col-md-6">
              <h4>Unit Price</h4>
            </div>
            <div class="col-md-6">
              <h4><b><%=number_to_currency @jcart['unit_price'] %></b></h4>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <h4>Quantity</h4>
            </div>
            <div class="col-md-6">
              <h4><b><%=@jcart['quantity']%></b></h4>
            </div>
          </div>
          
          <div class="row">
            <div class="col-md-6">
              <h4>Discount</h4>
            </div>
            <div class="col-md-6">
              <h4><b>$0</b></h4>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-md-6">
              <h4>Total price</h4>
            </div>
            <div class="col-md-6">
              <h4 style="color: #00becc"><b><%= number_to_currency @jcart['total_price'] %></b></h4>
            </div>
          </div>   
          <div class="row">
            <div class="col-md-12">
              <p style="opacity: 0.5"><b>Included:</b> service 10%, tax 10%</p>
            </div>
          </div>
        </div>       
  		</div>
    </div>
  </div>
</body>