config/routes.rb
Rails.application.routes.draw do
  get 'service_reviews/create'
  get "book_room", to: "services#book_room"
  get "pay", to: "services#pay"

  root "home#index"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers:{omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users, only: %i(index show destroy) do
    resources :schedules, only: %i(index create destroy) do
      resources :schedule_items, only: %i(index destroy edit create)
    end
  end
  get "/search", to: "home#search"
  get "services", to: "services#index"
  get "services/:id/confirm" , to: "services#confirm", :as => :service_confirm
  get "services/categories/:category_id", to: "services#index", :as => :service_categories
  get "services/:id" , to: "services#show", :as => :service_details
  resources :service_reviews, only: %i(create destroy)

  get "service_bookings/payment" , to: "service_bookings#payment", :as => :service_payment
  resources :service_bookings
  get "services_in_place/:place_id", to: "services#services_in_place", :as => :services_in_place

end

app/models/schedule_item.rb
class ScheduleItem < ApplicationRecord
  belongs_to :schedule
  belongs_to :category
  has_one :schedule_item_image, dependent: :destroy
end

app/controllers/schedule_items_controller.rb
class ScheduleItemsController < ApplicationController
    before_action :authenticate_user!
    before_action :load_category, only: %i(index)
    
    def index
        @schedule = Schedule.find_by id: params[:schedule_id]
        @schedule_items = @schedule.schedule_items.order(created_at: :desc)
    end
    

    def destroy
        @schedule_item_id = params[:id]
        @item = ScheduleItem.find_by id: params[:id]
        @item.destroy
        respond_to do |format|
          format.html
          format.js
        end
    end
    
    def create
        @schedule = Schedule.find_by(id: params[:schedule_id])
        @schedule_item = @schedule.schedule_items.build schedule_item_params
        @schedule_item.save
        respond_to do |format|
            format.html
            format.js
        end
    end
    
    def schedule_item_params
        params.require(:schedule_item).permit(:category_id, :description, :start_time, :end_time)
    end
    
    def load_category
        @categories = Category.all
    end
end

app/views/schedule_items/_create_schedule_item.html.erb
<div class="modal" id="create-schedule-item-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">
          Create new item
          <i class="far fa-calendar-alt fa-lg"></i>
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <div class="modal-body">
      <%= form_for(@schedule.schedule_items.build,:url => user_schedule_schedule_items_path(current_user.id, @schedule.id), remote: true) do |f| %>
        <div class="form-group">
          <%= f.label :category, class: "col-form-label" %>
          <%= f.collection_select :category_id, @categories, :id, :name, include_blank: true, required: true%>
        </div>
        <div class="form-group">
          <%= f.label :description, class: "col-form-label" %>
          <%= f.text_field :description, required: true, class: "form-control" %>
        </div>
        <div class = "form-group row">
          <div class="col-md-4">
            <%= f.label :start_time, class: "col-form-label" %>
            <%= f.date_field :start_time, required: true %>
          </div>
        
          <div class="col-md-4">
            <%= f.label :end_time, class: "col-form-label" %>
           <%= f.date_field :end_time, required: true %>
          </div>
        </div>
        <%= f.submit t("button.create"), class: "btn btn-primary" %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/schedule_items/_schedule_item.html.erb
<div id="item-<%= schedule_item.id %>">
    <!-- List group-->
    <ul class="list-group shadow">
        <!-- list group item-->
        <li class="list-group-item">
            <!-- Custom content-->
            <div class="media align-items-lg-center flex-column flex-lg-row p-3">
                <div class="media-body order-2 order-lg-1">
                    <h4 class="mt-0 font-weight-bold mb-2"><strong><%= schedule_item.category.name %></strong></h4>
                    <p class="font-italic text-muted mb-0 small"><%= schedule_item.description %></p>
                    <div class="d-flex align-items-center justify-content-between mt-1">
                        <h6 class="font-weight-bold my-2">Timeline: <%= date_string_for schedule_item.start_time %> - <%= date_string_for schedule_item.end_time %></h6>
                        <ul class="list-inline small">
                            <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                            <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                            <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                            <li class="list-inline-item m-0"><i class="fa fa-star text-success"></i></li>
                            <li class="list-inline-item m-0"><i class="fa fa-star-o text-gray"></i></li>
                        </ul>
                    </div>
                <% if schedule_item.schedule_item_image %>
                </div><img src=<%= schedule_item.schedule_item_image.link %> alt="Generic placeholder image" width="180" class="ml-lg-5 order-1 order-lg-2">
                <% end %>
                <%= link_to t("button.search_service"), service_categories_path(schedule_item.category.id),:style=> "float:right;" %>
                <br></br>
                <i class="fas fa-edit"></i> <%= t "button.edit" %>
    			
    			<%= link_to user_schedule_schedule_item_path(current_user.id, @schedule.id, schedule_item.id), method: :delete,
                 data: { confirm: t("dialog.delete_schedule_item_confirm"),remote: true }, style: "float: right;" do %>
                    <i class="fas fa-trash-alt"></i> <%= t "button.delete" %>
                <% end %>
            </div> <!-- End -->
    </ul>
</div>

app/views/schedule_items/create.js.erb
$("#list-new-schedule-items").append("<%= escape_javascript(render :partial => 'schedule_item', :locals => {:schedule_item => @schedule_item}) %>");
$("#create-schedule-item-modal").modal("hide");
toastr.success("Create Schedule Item successful!");

app/views/schedule_items/destroy.js.erb
$("#item-<%= @schedule_item_id %>").fadeOut();
toastr.success("Delete schedule_item success!");

app/views/schedule_items/index.html.erb
<div class="row">
  <div class="col-md-2">&nbsp;</div>
  <div class="col-md-8">
    <div class="row space-16">&nbsp;</div>
    <div class="row">
        <div class="col-sm-4">
            <div class="thumbnail custom-fix-size">
              <div class="caption text-center">
                <div class="position-relative">
                   <img src="https://cdn-image.travelandleisure.com/sites/default/files/styles/1600x1000/public/1543939668/sharjah-united-arab-emirates-sunset-WTG20191218.jpg?itok=-4H2dY0d" class= "custom-card-image" alt="Resort at Boracay, Philippines">
                </div>
                <h4 id="thumbnail-label"><strong><%=@schedule.name%></strong></h4>

                <div class="smaller">
                   by <strong><%=@schedule.user.name%></strong>
                </div>

                <div class="smaller">
                  <%= @schedule.description %>
                </div>
              </div>
              <div class="caption card-footer text-center">
                <ul class="list-inline">
                  <%=  date_string_for @schedule.created_at %>
                </ul>
                <ul class="caption text-center">
                  <a data-toggle="modal" data-target="#create-schedule-item-modal">
                    <h4><i class="fas fa-plus-circle fa-2x"></i></h4>
                  </a>
                </ul>
              </div>

            </div>
        </div>
        <div class="col-sm-8 mx-auto">
        <div id="list-new-schedule-items">
        </div>
        <% @schedule_items.each  do |s| %>
          <%= render :partial => "schedule_item", :locals => {:schedule_item => s } %>
        <% end %>
        </div>
  </div>
</div>
<div>
<%= render :partial => "create_schedule_item" %>