config/routes.rb
Rails.application.routes.draw do
  get 'service_reviews/create'
  get "book_room", to: "services#book_room"
  get "pay", to: "services#pay"

  root "home#index"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers:{omniauth_callbacks: "users/omniauth_callbacks"}
  resources :users, only: %i(index show destroy) do
    resources :schedules, only: %i(index create destroy) do
      resources :schedule_items, only: %i(index destroy edit create)
    end
  end
  get "/search", to: "home#search"
  get "services", to: "services#index"
  get "services/:id/confirm" , to: "services#confirm", :as => :service_confirm
  get "services/categories/:category_id", to: "services#index", :as => :service_categories
  get "services/:id" , to: "services#show", :as => :service_details
  resources :service_reviews, only: %i(create destroy)

  get "service_bookings/payment" , to: "service_bookings#payment", :as => :service_payment
  resources :service_bookings
  get "services_in_place/:place_id", to: "services#services_in_place", :as => :services_in_place

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Service

    if user.present?
        can :show, User, id: user.id
        if user.has_role? :admin
            can :access, :rails_admin
            can :read, :dashboard
            can :manage, [User, Provider, Category]
            can :read, [ServiceBooking]
        end

    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking_status.rb
class BookingStatus < ApplicationRecord
    has_many :service_bookings
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  resourcify
  has_many :hotel_images, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :images, through: :hotel_images, dependent: :destroy
  accepts_nested_attributes_for :hotel_images, allow_destroy: true
  accepts_nested_attributes_for :images, allow_destroy: true
end
# include PgSearch
# pg_search_scope :search_by_full_name, against: [:name, :city]

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
end

app/models/place.rb
class Place < ApplicationRecord
  # resourcify
    has_many :services
    scope :order_by_name, ->(_name){order :name}
    scope :get_places, ->(name){where("name like ?", "%#{name}%")}
    scope :popular_places, ->{order(:id).take Settings.popular_places}

    def popular_places
        Place.joins(:services).select("places.*, count(services.id) as scount").group("places.id").order("scount DESC").take(Settings.popular_places)
    end
end

app/models/provider.rb
class Provider < ApplicationRecord
    has_many :services, dependent: :destroy
end

app/models/review_image.rb
class ReviewImage < ApplicationRecord
  belongs_to :service_review
  mount_uploader :link,  AvatarUploader
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
  has_many :schedule_items, dependent: :destroy
end

app/models/schedule_item.rb
class ScheduleItem < ApplicationRecord
  belongs_to :schedule
  belongs_to :category
  has_one :schedule_item_image, dependent: :destroy
end

app/models/schedule_item_image.rb
class ScheduleItemImage < ApplicationRecord
    mount_uploader :link , AvatarUploader
    belongs_to :schedule_item
end

app/models/service.rb
class Service < ApplicationRecord
  resourcify
  belongs_to :provider
  belongs_to :category
  belongs_to :place
  has_many :service_images, dependent: :destroy
  has_many :service_reviews
  scope :get_services, ->(place_id,start_time, end_time){where("place_id = ?", place_id).where("start_time = ?", start_time.to_datetime).where("end_time = ?", end_time.to_datetime)}
  scope :get_by_category, ->(id){where("category_id = ?", id)}
  scope :get_services_in_place, ->(id){where("place_id = ?", id)}
end

app/models/service_booking.rb
class ServiceBooking < ApplicationRecord
  belongs_to :user
  belongs_to :service
  belongs_to :payment_method
  belongs_to :booking_status

  before_create :set_booking_status

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :user_id, presence: true
  validates :service_id, presence: true
  validates :booking_address, presence: true
  validates :payment_method_id, presence: true
  validates :booking_user, presence: true
  validates :booking_status, presence: true

  def subtotal

  end

  def user_name
    self.user.name
  end

  def generate_qr text
    chart = GoogleQR.new(:data => "#{text}", :size => "250x250", :margin => 4, :error_correction => "L")
    return chart.to_s
  end

  private
  def set_booking_status
    self.booking_status_id = 1
  end

end

app/models/service_image.rb
class ServiceImage < ApplicationRecord
  belongs_to :service
end

app/models/service_review.rb
class ServiceReview < ApplicationRecord
  belongs_to :user
  belongs_to :service
  has_many :review_images, dependent: :destroy
  
  accepts_nested_attributes_for :review_images, allow_destroy: true,
    reject_if: proc{|attributes| attributes["image"].blank?}
end

app/models/user.rb
class User < ApplicationRecord
  rolify

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]
  mount_uploader :avatar, AvatarUploader


  after_create :assign_default_role
  scope :ordered_by_name, ->{order :name}
  # validates :name, :presence => true
  # validates :name, :uniqueness => true
  has_many :schedules, dependent: :destroy
  has_many :service_reviews, dependent: :destroy

  has_many :service_bookings

  def self.new_with_session params, session
    super.tap do |user|
      if data = session["devise.facebook_data"] &&
        session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def assign_default_role
    self.add_role(:moderator) if self.roles.blank?
  end

  def self.from_omniauth auth
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def date_string_for(datetime)
        datetime.strftime("%b %e, %Y") if datetime
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def get_avatar_for user, options = {size: Settings.user.avatar_size}
    width = options[:size]
    height = options[:size]
    avatar_url = if user.avatar?
                   user.avatar.url
                 else
                     Settings.user.default_avatar
                 end
    image_tag avatar_url,
      alt: user.name,
      class: "gravatar rounded-circle",
      id: "img_prev",
      width: width,
      height: height
  end
end

app/views/layouts/_banner.html.erb
<div class="full-row banner">
    <!-- Carousel head -->
    <div id="carousel-banner-picture" class="carousel slide " data-ride="carousel" data-interval="8000">
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <%= link_to image_tag("banner-12.jpg", alt: "Hoi An", class: "img-responsive banner-img"), "#" %>
                <div class="carousel-caption">
                    <p class="nation-caption"><span><%= t "Viet_Nam" %></span></p>
                    <h1 class="location-caption"><%= t "Sheraton_Ha_Noi" %></h1>
                </div>
            </div>
            <div class="item">
                <%= link_to image_tag("banner-11.jpg", alt: "Hoi An", class: "img-responsive banner-img"), "#" %>
                <div class="carousel-caption">
                    <p class="nation-caption"><span><%= t "Viet_Nam" %></span></p>
                    <h1 class="location-caption"><%= t "Villa_Da_Nang" %></h1>
                </div>
            </div>
            <div class="item">
                <%= link_to image_tag("banner-14.jpg", alt: "Hoi An", class: "img-responsive banner-img"), "#" %>
                <div class="carousel-caption">
                    <p class="nation-caption"><span><%= t "Viet_Nam" %></span></p>
                    <h1 class="location-caption"><%= t "Luxury_Hoi_An" %></h1>
                </div>
            </div>
            <div class="item">
                <%= link_to image_tag("banner-13.jpg", alt: "Hoi An", class: "img-responsive banner-img"), "#" %>
                <div class="carousel-caption">
                    <p class="nation-caption"><span><%= t "Viet_Nam" %></span></p>
                    <h1 class="location-caption"><%= t "Magestic_Sai_Gon" %></h1>
                </div>
            </div>
            <div class="item">
                <%= link_to image_tag("banner-15.jpg", alt: "Hoi An", class: "img-responsive banner-img"), "#" %>
                <div class="carousel-caption">
                    <p class="nation-caption"><span><%= t "Viet_Nam" %></span></p>
                    <h1 class="location-caption"><%= t "JW_Marriott_Phu_Quoc" %></h1>
                </div>
            </div>
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#carousel-banner-picture" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-banner-picture" data-slide-to="1"></li>
                <li data-target="#carousel-banner-picture" data-slide-to="2"></li>
                <li data-target="#carousel-banner-picture" data-slide-to="3"></li>
                <li data-target="#carousel-banner-picture" data-slide-to="4"></li>
            </ol>
        </div>
        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-banner-picture" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only"></span>
        </a>
        <a class="right carousel-control" href="#carousel-banner-picture" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only"></span>
        </a>
    </div>
    <!-- .Carousel head -->
</div>
<!-- .full row-Banner -->

app/views/layouts/_filter_hotel.html.erb
<div class="col-xs-12 col-sm-3 page-left filter-left-mb__overlay">
    <div class="filter-head__overlay">
        <h3><%= t "Filter" %></h3>
        <span class="fa fa-close filter-head-close__overlay"></span>
    </div>
    <div class="filter-left">
        <div class="filter-head">
            <h3><%= t "Filter_Results" %> <span class="pull-right reset-filter"><%= t "Reset_Filter" %></span></h3>
            <p><%= t "Showing_results" %></p>
        </div>
        <!-- Budget -->
        <filter class="box box-filter-budget">
            <div class="filter-title">
                <p><b><%= t "Your_Budget" %></b></p>
            </div>
            <div class="filter-inner">
                <ul class="list-group">
                    <li class="list-group-item">
                        <label class="text-blue">
                            <input type="checkbox" name="" value="" />
                            <span>VND 0 - VND 1,300,000 <%= t "per_night" %></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label class="text-blue">
                            <input type="checkbox" name="" value="" />
                            <span>VND 0 - VND 1,300,000 <%= t "per_night" %></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label class="text-blue">
                            <input type="checkbox" name="" value="" />
                            <span>VND 0 - VND 1,300,000 <%= t "per_night" %></span>
                    
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label class="text-blue">
                            <input type="checkbox" name="" value="" />
                            <span>VND 0 - VND 1,300,000 <%= t "per_night" %></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label class="text-blue">
                            <input type="checkbox" name="" value="" />
                            <span>VND 0 - VND 1,300,000 <%= t "per_night" %></span>
                        </label>
                    </li>
                </ul>
            </div>
        </filter>
        <!-- .Budget -->
        <!-- Star rating -->
        <filter class="box" id="accordioncollapseRating">
            <div class="filter-title">
                <p><%= t "Star_Rating" %><span class="fa fa-angle-down pull-right" role="button" data-toggle="collapse" data-parent="#accordioncollapseRating" href="#collapseRating" aria-expanded="true" aria-controls="collapseRating"></span></p>
            </div>
            <div class="filter-inner panel-collapse collapse in" id="collapseRating">
                <ul class="list-group">
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="5star" value="">
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star text-yellow"></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="5star" value="">
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star-o text-yellow"></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="5star" value="">
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star-o text-yellow"></span>
                            <span class="fa fa-star-o text-yellow"></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="5star" value="">
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star-o text-yellow"></span>
                            <span class="fa fa-star-o text-yellow"></span>
                            <span class="fa fa-star-o text-yellow"></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="5star" value="">
                            <span class="fa fa-star text-yellow"></span>
                            <span class="fa fa-star-o text-yellow"></span>
                            <span class="fa fa-star-o text-yellow"></span>
                            <span class="fa fa-star-o text-yellow"></span>
                            <span class="fa fa-star-o text-yellow"></span>
                        </label>
                    </li>
                </ul>
            </div>
        </filter>
        <!-- .Star rating -->
        <!-- Facilites -->
        <filter class="box" id="accordionFacilities">
            <div class="filter-title">
                <p class="text-blue"><%= t "Facilities" %> <span class="fa fa-angle-down pull-right" role="button" data-toggle="collapse" data-parent="#accordionFacilities" href="#collapseFacilities" aria-expanded="true" aria-controls="collapseFacilities"></span></p>
            </div>
            <div class="filter-inner panel-collapse collapse in" id="collapseFacilities">
                <ul class="list-group">
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="" value="" />
                            <span><%= t "WiFi" %></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="" value="" />
                            <span><%= t "Swimming_Pool" %></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="" value="" />
                            <span><%= t "Parking" %></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="" value="" />
                            <span><%= t "Restaurant" %></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="" value="" />
                            <span><%= t "Elevator" %></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="" value="" />
                            <span><%= t "Fitness_Center" %></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="" value="" />
                            <span><%= t "Meeting_Facilities" %></span>
                        </label>
                    </li>
                    <li class="list-group-item">
                        <label>
                            <input type="checkbox" name="" value="" />
                            <span><%= t "Airport_Transfer" %></span>
                        </label>
                    </li>
                </ul>
            </div>
        </filter>
    </div>
    <!-- .Filter left -->
</div>

app/views/layouts/_footer.html.erb
<footer class="full-row footer">
    <div class="container footer-content">
        <div class="row">
            <div class="col-xs-12 col-sm-3">
                <%= link_to image_tag("logo.png", alt: "logo", class: "img-responsive img-logo"), "#" %>
                <p><i><%= t "about_tripbricks" %></i></p>

            </div>
            <div class="col-xs-12 col-sm-3">
                <h3 class="text-uppercase"><b>Contact Info</b></h3>
                <p><span class="fa fa-map-marker text-yellow"></span> <%= Settings.address %></p>
                <p><span class="fa fa-phone text-yellow"></span> <%= Settings.telephone %></p>
                <p><span class="fa fa-envelope-o text-yellow"></span> <%= Settings.email_tripbricks %></p>
            </div>
            <div class="col-xs-12 col-sm-3">
                <h3 class="text-uppercase"><b><%= t "Discover" %></b></h3>
                <ul class="list-recent-post">
                    <li>
                        <a href="about_us"><%= t "About_Us" %></a>
                    </li>
                    <li>
                        <a href="term_condition"><%= t "Terms and conditions" %></a>
                    </li>
                    <li>
                        <a href="privacy_policy"><%= t "Privacy_policy" %></a>
                    </li>
                    
                </ul>
            </div>
            <div class="col-xs-12 col-sm-3">
                <h3 class="text-uppercase"><b><%= t "Connect_with_us" %></b></h3>
                <ul class="list-inline list-connect-us">
                    <li>
                      <%= link_to image_tag("icon-footer/fb.png", alt: "facebook", class: "img-responsive"), "https://www.facebook.com/quangleminh.leminh" %>
                    </li>
                    <li>
                      <%= link_to image_tag("icon-footer/sp.png", alt: "facebook", class: "img-responsive"), "https://www.facebook.com/quangleminh.leminh" %>
                    </li>
                    <li>
                      <%= link_to image_tag("icon-footer/tw.png", alt: "facebook", class: "img-responsive"), "https://www.facebook.com/quangleminh.leminh" %>
                    </li>
                    <li>
                      <%= link_to image_tag("icon-footer/yt.png", alt: "facebook", class: "img-responsive"), "https://www.facebook.com/quangleminh.leminh" %>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<% if current_page?(root_path) || current_page?("/") %>
  <header class="">
<% else %>
  <header class="black-header">
<% end %>
    <nav class="navbar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-3">
                    <span class="sr-only"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to image_tag("logo.png", alt: "logo", class: "img-responsive pull-left img-logo logo-web"), root_path %>
            </div>
            <div class="collapse navbar-collapse navbar" id="navbar-collapse-3">
                <ul class="nav navbar-nav navbar-left">
                    <li><%= link_to t("Hotels"), services_path %></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="li-number">
                        <a href="tel:+84 (0) 98 453 0860"><span class="fa fa-phone text-violet"></span><%= Settings.telephone %></a>
                    </li>
                    <li class="header-login-register">
                      <% if user_signed_in? %>
                        <% if current_user.has_role? :admin %>
                            <%= link_to "Dashboard", rails_admin_path %>
                        <% else %>
                            <%= link_to t("profile"), current_user %>
                            <%= link_to t("My Schedules"), user_schedules_path(current_user)%>
                         <% end %>
                        <%= link_to t("logout"), destroy_user_session_path, method: :delete %>
                      <% else %>
                        <%= link_to t("login"), new_user_session_path %>
                        <%= link_to t("signup"), new_user_registration_path %>
                      <% end %>
                    </li>
                </ul>
                <div class="collapse nav navbar-nav nav-collapse" id="nav-collapse3">
                    <form class="navbar-form navbar-right" role="search">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Search" />
                        </div>
                        <button type="submit" class="btn btn-danger"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                    </form>
                </div>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/_search_form.html.erb
<div class="full-row form_tour_search">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
        <!--<form id="tour_search_form" name="tour_search_form" method="get" action="">-->
        <%= form_tag search_path, method: :get, id:"tour_search_form" do %>
            <div class="tour_search_wrapper">
                <div class="col-xs-12 col-sm-3 one_fourth">
                    <label for="keyword"><%= t "Destination" %></label>
                    <!--<input id="keyword" class="form-control" name="keyword" type="text" placeholder="City, region or keywords">-->
                    <%= text_field_tag :name, params[:name], class:"form-control", placeholder:"City, region or keywords" %>
                </div>
                <div class="col-xs-12 col-sm-3 one_fourth">
                    <label for="col-xs-12 start_date"><%= t "Date" %></label>
                    <div class="row">
                        <div class="col-xs-6 start_date_input">
                            <%= date_field_tag :from, params[:from], :value => Time.now.strftime('%Y-%m-%d'), placeholder:"From", class:"form-control hasDatepicker"%>
                        </div>
                        <div class="col-xs-6 end_date_input">
                            <%= date_field_tag :to, params[:to], placeholder:"To", class:"form-control hasDatepicker"%>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-3 one_fourth">
                    <label for="guests"><%= t "Guests" %></label>
                    <input id="guests" class="form-control" name="guests" type="text" placeholder="0 - Adults">
                </div>
                <div class="col-xs-12 col-sm-3 one_fourth last">
                    <input id="tour_search_btn" class="btn btn-blue" type="submit" value="Search">
                </div>
            </div>
        <% end %>
        <!--</form>-->
    </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Confasche.com</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <div id="wrapper">
      <%= render "layouts/header" %>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>